### ISSUE TITLE
cloudify-stage-* does not exists on simple-manager bootstrap

### ISSUE THREAD

**Issue by emepetres** [cloudify-cosmo/cloudify-manager-blueprints#587]
I'm trying to bootstrap a manager in a local Centos 7 vagrant (VirtualBox) machine using CLI 4.0 installed on windows 7.

The process goes as expected until it comes to this error:
**File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources** when installing cloudify stage

I'm using simple-manager-blueprint (4.0 version) defining the public and private vagrant machine ip, username, ssh key file. The virtual machine is a clean image of last Centos 7.

Below the pertinent log piece:
> LOG <manager> [stage_72fo29.create] INFO: Installing Cloudify Stage (UI)...
> out: File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources
> out: Traceback (most recent call last):
> out:   File "/tmp/cloudify-ctx/scripts/tmp5nnxpu-create.py-3NZI50I1", line 70, in <module>
> out:     main()
> out:   File "/tmp/cloudify-ctx/scripts/tmp5nnxpu-create.py-3NZI50I1", line 67, in main
> out:     install_stage()
> out:   File "/tmp/cloudify-ctx/scripts/tmp5nnxpu-create.py-3NZI50I1", line 54, in install_stage
> out:     STAGE_SERVICE_NAME)
> out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 427, in download_cloudify_resource
> out:     render=False)
> out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 1105, in create
> out:     resource_name)
> out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 1244, in _get_local_file_path
> out:     local_filepath = get_filepath_from_pkg_name(resource_name)
> out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 572, in get_filepath_from_pkg_name
> out:     format(filename, CLOUDIFY_SOURCES_PATH))
> out:   File "/tmp/cloudify-ctx/cloudify.py", line 234, in abort_operation
> out:     subprocess.check_call(cmd)
> out:   File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
> out:     raise CalledProcessError(retcode, cmd)
> out: subprocess.CalledProcessError: Command '['ctx', 'abort_operation', 'File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources']' returned non-zero exit status 1
> out:
> CFY <manager> [stage_72fo29.create] Task failed 'fabric_plugin.tasks.run_script' -> File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources
> CFY <manager> 'install' workflow execution failed: Workflow failed: Task failed 'fabric_plugin.tasks.run_script' -> File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources
> Bootstrap failed! (Workflow failed: Task failed 'fabric_plugin.tasks.run_script' -> File: cloudify-stage-*.tgz does not exist in sources path: /opt/cloudify/sources)
> Executing teardown due to failed bootstrap...

**Comment by tehasdf** [comment]
hmm, turns out the manager resources package in the inputs in the 4.0 git tag is incorrect after all. That sucks, sorry about that :(

If you go to the website at http://cloudify.co/download and download the package (eg. the RPM one), you'll find that it contains both the CLI, and the manager blueprint. The example inputs from the RPM, reference this manager resources package: http://repository.cloudifysource.org/cloudify/4.0.0/ga-release/cloudify-manager-resources_4.0.0-ga.tar.gz
Which seems to work with the 4.0 blueprint from git.

So please either use that URL (pass it as the `manager_resources_package` input), or switch to 4.0.1 CLI & blueprint (from git *should* work)

**Comment by emepetres** [comment]
Great @tehasdf, it worked! I imagined that it was a problem of the resources package, but I couldn't find the correct one as I cannot navigate through the cloudify files repository.

Closing this issue.
